import { Montserrat, Qwitcher_Grypen } from "next/font/google";
import "./globals.css";

const qwitcherGrypen = Qwitcher_Grypen({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-body",
});

const montserret = Montserrat({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-header",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${qwitcherGrypen.variable} ${montserret.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
