import { Qwitcher_Grypen } from "next/font/google";
import { Jacques_Francois_Shadow } from "next/font/google";
import "./globals.css";

const qwitcherGrypen = Qwitcher_Grypen({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-qwitcher-grypen",
});

const jacquesFrancoisShadow = Jacques_Francois_Shadow({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-jacques-francois-shadow",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${qwitcherGrypen.variable} ${jacquesFrancoisShadow.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
